### ISSUE TITLE
Provide binaries on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [azlyth/redub#1]
Please provide official binaries for download on the project's GitHub Releases page, particularly  an [AppImage](http://appimage.org/) for Linux.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

__electron-builder__ has built-in support for AppImage (in fact, it is already configured in this project's `package.json`.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by azlyth** [comment]
AppImage bot, eh?

I'll provide downloadable binaries once I get the project to v1.0.

**Comment by azlyth** [comment]
Binaries are now indeed available on the Releases.
